/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */

const evenFibonacci = function() {
	let sum = 0;
	let fibonacciNumbers = [1, 2];

	//return the sum of the last two values in the array
	function calculateValue(arr) {
	    return arr[arr.length - 1] + arr[arr.length - 2];
	}

	while (fibonacciNumbers[fibonacciNumbers.length - 1] < 4000000) {
	    fibonacciNumbers.push(calculateValue(fibonacciNumbers));
	}

	//for every number in the Fibonacci array
	fibonacciNumbers.forEach((element) => {
		//if they are even
	if (element % 2 === 0) {
		//add them to the sum
	      sum += element;
	    }
	});
	console.log(sum);
}();