/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */

const evenFibonacci = function() {
	let sum = 0;
	let a = 0;
	let b = 1;
	let next = 0;

	while(true) {
		next = a + b;
		a = b
		b = next
		if (next >= 4000000){
			break
		}
		if (next % 2 === 0) {
		//add them to the sum
	      sum += next;
	    }
	}

	console.log(sum);
}();